-- MySQL Script generated by MySQL Workbench
-- mié 13 dic 2023 18:57:18
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema zoo
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema zoo
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `zoo` ;
USE `zoo` ;

-- -----------------------------------------------------
-- Table `zoo`.`passports`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `zoo`.`passports` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `number` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  UNIQUE INDEX `number_UNIQUE` (`number` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `zoo`.`addresses`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `zoo`.`addresses` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `city` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `zoo`.`employees`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `zoo`.`employees` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `first_name` VARCHAR(45) NOT NULL,
  `last_name` VARCHAR(45) NOT NULL,
  `passport_id` BIGINT UNSIGNED NOT NULL,
  `address_id` BIGINT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_employees_passports_idx` (`passport_id` ASC) VISIBLE,
  INDEX `fk_employees_addresses1_idx` (`address_id` ASC) VISIBLE,
  CONSTRAINT `fk_employees_passports`
    FOREIGN KEY (`passport_id`)
    REFERENCES `zoo`.`passports` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_employees_addresses1`
    FOREIGN KEY (`address_id`)
    REFERENCES `zoo`.`addresses` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `zoo`.`departments`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `zoo`.`departments` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `zoo`.`enclosures`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `zoo`.`enclosures` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `type` ENUM("AQUARIUM", "AVIARY", "TERRARIUM") NOT NULL,
  `capacity` INT NOT NULL,
  `department_id` BIGINT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_enclosures_sectors1_idx` (`department_id` ASC) VISIBLE,
  CONSTRAINT `fk_enclosures_sectors1`
    FOREIGN KEY (`department_id`)
    REFERENCES `zoo`.`departments` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `zoo`.`species`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `zoo`.`species` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `habitat` VARCHAR(45) NULL,
  `average_lifespan_in_years` TINYINT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `zoo`.`animals`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `zoo`.`animals` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `species` VARCHAR(45) NOT NULL,
  `enclosure_id` BIGINT UNSIGNED NOT NULL,
  `species_id` BIGINT UNSIGNED NOT NULL,
  `gender` ENUM("MALE", "FEMALE") NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_animals_enclosures1_idx` (`enclosure_id` ASC) VISIBLE,
  INDEX `fk_animals_species1_idx` (`species_id` ASC) VISIBLE,
  CONSTRAINT `fk_animals_enclosures1`
    FOREIGN KEY (`enclosure_id`)
    REFERENCES `zoo`.`enclosures` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_animals_species1`
    FOREIGN KEY (`species_id`)
    REFERENCES `zoo`.`species` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `zoo`.`visitors`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `zoo`.`visitors` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `first_name` VARCHAR(45) NOT NULL,
  `last_name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `zoo`.`events`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `zoo`.`events` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `date` TIMESTAMP NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `zoo`.`tickets`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `zoo`.`tickets` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `number` VARCHAR(45) NOT NULL,
  `day` TIMESTAMP NULL,
  `event_id` BIGINT UNSIGNED NOT NULL,
  `price` DOUBLE NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  UNIQUE INDEX `number_UNIQUE` (`number` ASC) VISIBLE,
  INDEX `fk_tickets_events1_idx` (`event_id` ASC) VISIBLE,
  CONSTRAINT `fk_tickets_events1`
    FOREIGN KEY (`event_id`)
    REFERENCES `zoo`.`events` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `zoo`.`employee_departments`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `zoo`.`employee_departments` (
  `employee_id` BIGINT UNSIGNED NOT NULL,
  `department_id` BIGINT UNSIGNED NOT NULL,
  PRIMARY KEY (`employee_id`, `department_id`),
  INDEX `fk_employees_has_departments_departments1_idx` (`department_id` ASC) VISIBLE,
  INDEX `fk_employees_has_departments_employees1_idx` (`employee_id` ASC) VISIBLE,
  CONSTRAINT `fk_employees_has_departments_employees1`
    FOREIGN KEY (`employee_id`)
    REFERENCES `zoo`.`employees` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_employees_has_departments_departments1`
    FOREIGN KEY (`department_id`)
    REFERENCES `zoo`.`departments` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `zoo`.`veterinarians`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `zoo`.`veterinarians` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `specialization` VARCHAR(45) NOT NULL,
  `first_name` VARCHAR(45) NOT NULL,
  `last_name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `zoo`.`animal_veterinarians`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `zoo`.`animal_veterinarians` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `animals_id` BIGINT UNSIGNED NOT NULL,
  `veterinarians_id` BIGINT UNSIGNED NOT NULL,
  `visit_day` TIMESTAMP NOT NULL,
  `diagnosis` VARCHAR(150) NOT NULL,
  PRIMARY KEY (`id`, `animals_id`, `veterinarians_id`),
  INDEX `fk_animals_has_veterinarians_veterinarians1_idx` (`veterinarians_id` ASC) VISIBLE,
  INDEX `fk_animals_has_veterinarians_animals1_idx` (`animals_id` ASC) VISIBLE,
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  CONSTRAINT `fk_animals_has_veterinarians_animals1`
    FOREIGN KEY (`animals_id`)
    REFERENCES `zoo`.`animals` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_animals_has_veterinarians_veterinarians1`
    FOREIGN KEY (`veterinarians_id`)
    REFERENCES `zoo`.`veterinarians` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `zoo`.`visitor_tickets`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `zoo`.`visitor_tickets` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `visitor_id` BIGINT UNSIGNED NOT NULL,
  `ticket_id` BIGINT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`, `visitor_id`, `ticket_id`),
  INDEX `fk_visitors_has_tickets_tickets1_idx` (`ticket_id` ASC) VISIBLE,
  INDEX `fk_visitors_has_tickets_visitors1_idx` (`visitor_id` ASC) VISIBLE,
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  CONSTRAINT `fk_visitors_has_tickets_visitors1`
    FOREIGN KEY (`visitor_id`)
    REFERENCES `zoo`.`visitors` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_visitors_has_tickets_tickets1`
    FOREIGN KEY (`ticket_id`)
    REFERENCES `zoo`.`tickets` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
